### PR TITLE
added support for client ids and TLSv1.2

### PR DESCRIPTION
**Pull request by macmeck**
Hi, I have added another parameter to provide individual MQTT client ids. Might be necessary for some setups. Would be great if you could merge the changes into the main branch.

### CODE REVIEW

**Comment by macmeck** [comment]
In the meantime, I have included TLSv1.2 support!

Important to know: a valide CA certificate needs to be available on the Android device. Either one that is automatically being trusted or a self-created CA that has been added manually

**Comment by nosybore** [comment]
Thanks! Sorry it took me so long to get around to this. I'll try to get this merged and pushed out to the play store this weekend.

**Comment by TRIROG** [comment]
Is there any way to also add the subscription support?
I would love to use MQTT to signal Tasker to execute some tasks.

**Comment by oliverlorenz** [comment]
+1 subscription support

**Comment by xsertunc** [comment]
+1 subscriptions , would be great!

**Pull request merged**
